question_data = [{"question": "[white]Darth Vader tells you he's your father. What do you do?:[/]\n\n[black]A. Kill him and take his place\n\nB. Try and convince him to be a good dad and turn to the good side of the force\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You find out a co-worker is gossiping about you, how do you handle it?:[/]\n\n[black]A. Introduce them to a left hook\n\nB. Ignore it\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather talk like Yoda or breathe like Darth Vader?\n\n[black]A. Talk like Yoda\n\nB. Breathe like Darth Vader\n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]How do you handle road rage when somone cuts you off?:\n\n[black]A. Try and cut them off too so they get a taste of thier own medicine\n\nB. Practice taking deep breaths whenever some one cut you off\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Your due for a new starfighter what catches your eye when you get to the shipyard:\n\n[black]A. TIE/x1 starfighter\n\nB. T65 X-wing starfighter\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You find a wallet on the sidewalk filled with cash and the owner's driver's license. What do you do?:\n\n[black]A. Send the wallet back to the owner\nB. Send the wallet back to the owner but keep the money\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You are exhausted from marking terminal app assignments all week and decide to book a holiday. What destination did you choose?:\n\n[black]A. Peaceful planet of Sorgan. A world dotted by ramshackle villages where farmers spend their days fishing for krill in the wetlands,\n\nB. Planet Mustafar, a lava planet, full of volcanoes and awful mines.\n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather get a tattoo of Jar-Jar Binks on your neck, or be woken up every morning by being slapped in the face?\n\n[black]A. Slapped in the face\n\nB. Tattoo \n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather be frozen in carbonite or serve under Darth Vader:\n\n[black]A. Serve under Darth Vader\n\nB. Frozen in carbonite\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather have a drink at the Death Star bar or the bar at Mos Eisley?\n\n[black]A. Death Star bar\nB. Mos Eisley bar\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""}]
quest_data = [{"question": "\n[yellow ]You arrive at the Jedi temple on the ice planet of Ilum to seek a Kyber crystal so you can build your light sabre. You hear a song playing in the distance. What do you do\n\n[black]A. You trust your insticts and Follow the sound\nB. wlak in the opposit direction \n",
               "correct_answer": "A",
               "incorrect_answers": "[black bold] You walk in the opposit direction and slip over and die "},
              {"question": "\nyou get to the source of the music and you notice its a kyber crystal, then all of a sudden you notice a large Rancor crawls out from a cave what do you do?\n\n[black]A. you ru and hide behind the nearest rock in the cave\nB. you relize its the kyber crystal is testing you to overcome your fear and you charge at the rancor\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] you start running and trip over and nock you head againt the rock you wanted to hide behind and bleed out "},
              {"question": "\nwhen you get close to the rancor it disapears so you grab the kyber crytal and relise you have to ecape the ice cave before it frezes shut you start running back to were you came from and you get to a fork in the cave and you cant remeber whic way what do you do?\n\nA. Go left\nB. Go right\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] you go left and when you get to end of the cave you relise it was the long way and the cave entrance has frozen over you freeze to death "},
              {"question": "\nyears later...... you are on a mission with your jedi master were you have to meet with Trade Federation Viceroy to discus a trivall trade dipute while waitng in a room on the Commanding Viceroy ship you notice Dioxis gas comming out of the vents and then room locks what do you do\n\nA. just crack a window in the ship let the gas seep out into space\nB. hold you breath for long as you can until they think you are dead\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] you crack a window open with you light saber and instanly get sucked in to space a suffocate "},
              {"question": "\nThe doors open and you and you race out with your master and make haste and destroy all enemy droids that are in your way, you reach the room  that the Commanding Viceroy is in but the blast doors colse and lock you out than you notice destroyer roll in and start shooting out you what do you do\n\nA. They have shields so you use your jedi speed and escape\nB. you stand your ground you cant let the Commanding Viceroy get away with trying to kill you and your master\n",
               "correct_answer": "A",
               "incorrect_answers": "[black bold] The shileds on the battle droids a to strong you and your master are killed "}]
