question_data = [{"question": "[white]Darth Vader tells you he's your father. What do you do?:[/]\n\n[black]A. Kill him and take his place\n\nB. Try and convince him to be a good dad and turn to the good side of the force",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You find out a co-worker is gossiping about you, how do you handle it?:[/]\n\n[black]A. Introduce them to a left hook\n\nB. Ignore it\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather talk like Yoda or breathe like Darth Vader?\n\n[black]A. Talk like Yoda\n\nB. Breathe like Darth Vader\n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]How do you handle road rage when somone cuts you off?:\n\n[black]A. Try and cut them off too so they get a taste of thier own medicine\n\nB. Practice taking deep breaths whenever some one cut you off\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Your due for a new starfighter what catches your eye when you get to the shipyard:\n\n[black]A. TIE/x1 starfighter\n\nB. T65 X-wing starfighter\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You find a wallet on the sidewalk filled with cash and the owner's driver's license. What do you do?:\n\n[black]A. Send the wallet back to the owner\nB. Send the wallet back to the owner but keep the money\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]You are exhausted from marking terminal app assignments all week and decide to book a holiday. What destination did you choose?:\n\n[black]A. Peaceful planet of Sorgan. A world dotted by ramshackle villages where farmers spend their days fishing for krill in the wetlands,\n\nB. Planet Mustafar, a lava planet, full of volcanoes and awful mines.\n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather get a tattoo of Jar-Jar Binks on your neck, or be woken up every morning by being slapped in the face?\n\n[black]A. Slapped in the face\n\nB. Tattoo \n",
                  "correct_answer": "A",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather be frozen in carbonite or serve under Darth Vader:\n\n[black]A. Serve under Darth Vader\n\nB. Frozen in carbonite\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""},
                 {"question": "[white]Would you rather have a drink at the Death Star bar or the bar at Mos Eisley?\n\n[black]A. Death Star bar\nB. Mos Eisley bar\n",
                  "correct_answer": "B",
                  "incorrect_answers": ""}]
quest_data = [{"question": "You arrive at the Jedi temple on the ice planet of Ilum to seek a Kyber crystal so you can build your light sabre. You hear a song playing in the distance. What do you do?\n\n[black]A. You trust your instincts and Follow the sound.\n\nB. ignore it and Walk in the opposite direction \n",
               "correct_answer": "A",
               "incorrect_answers": "[black bold] You walk in the opposit direction and slip over and die "},
              {"question": "You get to the source of the music, and you notice it's a kyber crystal, then suddenly, you see a giant Rancor crawling out from a cave. What do you do?\n\n[black]A. You run and hide behind the nearest rock in the cave\n\nB. You realize it's the kyber crystal, and it is testing you to overcome your fear, so you charge at the rancor\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] You start running, but the rancor catches you and kills you instantly "},
              {"question": "When you get close to the rancor it disappears, so you grab the kyber crystal and realise you have to escape the ice cave before the entrance freezes shut. You start running back to where you came from, and you get to a fork in the cave, and you can't remember which way. What do you do?\n\n[black]A. Go left\n\nB. Go right\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] You get to the end of the cave, and you realise it was the wrong way. The cave entrance has frozen over. You freeze to death "},
              {"question": "Years later...... you are on a mission with your Jedi master where you have to meet with Trade Federation Viceroy to discuss a trivial trade dipute. While waiting in a room on the Commanding Viceroy ship, you notice Dioxis gas coming out of the vents, and then the room locks. What do you do?\n\n[black]A. just crack a window in the ship let the gas seep out into space\n\nB. hold you breath for long as you can until they think you are dead\n",
               "correct_answer": "B",
               "incorrect_answers": "[black bold] You crack a window open with your light sabre and instantly get sucked into space a suffocate "},
              {"question": "The doors open, and you and you race out with your master and destroy all enemy droids in your way. You reach the room that the Commanding Viceroy is in, but the blast doors close and lock you out. Then you notice destroyer droids roll in and start shooting out you. What do you do?\n\n[black]A. Their shields are too strong, so you use your Jedi speed and escape\n\nB. you stand your ground you cant let the Commanding Viceroy get away with trying to kill you and your master\n",
               "correct_answer": "A",
               "incorrect_answers": "[black bold] The shields on the battle droids a too strong you and your master are killed. "}]
